[package]
name = "stochastic_filter_bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "^0.3.1"
rand = "^0.8.4"
stochastic_filter = { path = "../stochastic_filter" }
